CREATE PROCEDURE [dbo].[spDeleteProductSalesSubRegion]
	@productSalesSubRegionId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE FROM [dbo].[ProductSalesSubRegion]
		WHERE [ProductSalesSubRegionId] = @productSalesSubRegionId

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END