CREATE PROCEDURE [dbo].[spDeleteOrderLineItemStatus]
	@orderLineItemStatusId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE OLIS
		FROM [dbo].[OrderLineItemStatus] OLIS
		INNER JOIN [dbo].[MasterDataType] MDT ON OLIS.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE OLIS.[OrderLineItemStatusId] = @orderLineItemStatusId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END