namespace CRM.Model
{
    public enum FunctionTitle
    {
        AccountManager,
        CompanyConfiguration,
        Country,
        Currency,
        CurrencyConversion,
        Customer,
        CustomerContact,
        CustomerLead,
        CustomerLeadNote,
        CustomerLeadNoteType,
        CustomerLeadStatus,
        CustomerLeadStatusHistory,
        CustomerLeadType,
        CustomerNote,
        CustomerNoteType,
        CustomerTier,
        CustomerType,
        DeliveryMethod,
        HTMLTemplate,
        HTMLTemplateType,
        Manufacturer,
        MarketingCampaign,
        MarketingCampaignMarketingChannel,
        MarketingCampaignStatus,
        MarketingCampaignStatusHistory,
        MarketingCampaignType,
        MarketingChannel,
        Order,
        OrderInvoice,
        OrderLineItem,
        OrderLineItemStatus,
        OrderLineItemStatusHistory,
        OrderPayment,
        OrderPaymentStatus,
        OrderPaymentStatusHistory,
        OrderQuote,
        OrderStatus,
        OrderStatusHistory,
        OrderType,
        PaymentMethod,
        Product,
        ProductCategory,
        ProductFamily,
        ProductImage,
        ProductNote,
        ProductNoteType,
        ProductSalesSubRegion,
        ProductSubCategory,
        ProductSupplier,
        Promotion,
        PromotionManufacturer,
        PromotionManufacturerProductCategory,
        PromotionManufacturerProductSubCategory,
        PromotionProduct,
        PromotionProductCategory,
        PromotionProductFamily,
        PromotionProductSubCategory,
        PromotionSupplier,
        PromotionSupplierProductCategory,
        PromotionSupplierProductSubCategory,
        PromotionTargetType,
        PromotionType,
        SalesRegion,
        SalesSubRegion,
        Supplier,
        SupplierContact,
        SupplierNote,
        SupplierNoteType,
        SupplierOrder,
        SupplierOrderLineItem,
        SupplierOrderLineItemStatus,
        SupplierOrderLineItemStatusHistory,
        SupplierOrderPayment,
        SupplierOrderPaymentStatus,
        SupplierOrderPaymentStatusHistory,
        SupplierOrderStatus,
        SupplierOrderStatusHistory,
        TaxProfile,
        WholesaleDeliveryType
    }

    public enum MeasurementType
    {
        Area,
        Distance,
        Liquid,
        Temperature,
        Volume,
        Weight
    }

    public enum LanguageRegionCode
    {
        czCZ,
        daDK,
        deDE,
        enGB,
        esES,
        fi,
        frFR,
        itIT,
        jaJP,
        ko,
        nbNO,
        nlNL,
        plPL,
        ptPT,
        svSE,
        zh
    }

    public enum ModuleGroup
    {
        CompanyManagement,
        CustomerManagement,
        MarketingManagement,
        OrderManagement,
        ProductManagement,
        SupplierManagement
    }

    public enum UnitType
    {
        Imperial,
        Metric
    }
}