CREATE PROCEDURE [dbo].[spDeleteCustomerNoteType]
	@customerNoteTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE CNT
		FROM [dbo].[CustomerNoteType] CNT
		INNER JOIN [dbo].[MasterDataType] MDT ON CNT.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE CNT.[CustomerNoteTypeId] = @customerNoteTypeId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END