CREATE PROCEDURE [dbo].[spDeleteHTMLTemplate]
	@htmlTemplateId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE FROM [dbo].[HTMLTemplate]
		WHERE [HTMLTemplateId] = @htmlTemplateId

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END