CREATE TABLE [dbo].[CustomerNote]
(
	[CustomerNoteId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[CustomerId] UNIQUEIDENTIFIER NOT NULL,
	[Note] NVARCHAR(MAX) NOT NULL,
	[Timestamp_Logged] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[LoggedBy] NVARCHAR(50) NOT NULL DEFAULT SUSER_NAME(),
	CONSTRAINT [FK_CustomerNote_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer]([CustomerId])
)