CREATE PROCEDURE [dbo].[spDeleteOrderLineItemDelivery]
	@orderLineItemDeliveryId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE FROM [dbo].[OrderLineItemDelivery]
		WHERE [OrderLineItemDeliveryId] = @orderLineItemDeliveryId

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END