CREATE PROCEDURE [dbo].[spDeleteProductNoteType]
	@productNoteTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE PNT
		FROM [dbo].[ProductNoteType] PNT
		INNER JOIN [dbo].[MasterDataType] MDT ON PNT.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE PNT.[ProductNoteTypeId] = @productNoteTypeId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END