CREATE PROCEDURE [dbo].[spDeletePromotionType]
	@promotionTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE PT
		FROM [dbo].[PromotionType] PT
		INNER JOIN [dbo].[MasterDataType] MDT ON PT.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE PT.[PromotionTypeId] = @promotionTypeId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END