CREATE PROCEDURE [dbo].[spDeletePalletPreset]
	@palletPresetId UNIQUEIDENTIFIER
AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE PP
		FROM [dbo].[PalletPreset] PP
		INNER JOIN [dbo].[MasterDataType] MDT ON PP.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE PP.[PalletPresetId] = @palletPresetId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END