CREATE PROCEDURE [dbo].[spCreateOrderStatusHistory]
	@orderId UNIQUEIDENTIFIER,
	@orderStatusId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

			INSERT INTO [dbo].[OrderStatusHistory]
			(
				[OrderId],
				[OrderStatusId]
			)
			VALUES
			(
				@orderId,
				@orderStatusId
			)

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END