CREATE PROCEDURE [dbo].[spDeleteSupplierNoteType]
	@supplierNoteTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE SNT
		FROM [dbo].[SupplierNoteType] SNT
		INNER JOIN [dbo].[MasterDataType] MDT ON SNT.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE SNT.[SupplierNoteTypeId] = @supplierNoteTypeId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END