CREATE PROCEDURE [dbo].[spGetCustomer]
	@customerId UNIQUEIDENTIFIER
AS

SELECT
[Global Parent Customer Id],
[Top Parent Customer Id],
[Customer Id],
[Account Manager],
[Account Manager Id],
[Customer Tier],
[Customer Tier Id],
[Customer Type],
[Sales Region],
[Sales Region Id],
[Sales Sub Region],
[Sales Sub Region Id],
[First Name],
[Last Name],
[Company Name],
[Telephone Number],
[Email Address],
[Billing First Name],
[Billing Last Name],
[Billing Company Name],
[Billing Address Line 1],
[Billing Address Line 2],
[Billing Address Line 3],
[Billing Address Line 4],
[Billing Address Line 5],
[Billing Telephone Number],
[Billing Email Address],
[Shipping First Name],
[Shipping Last Name],
[Shipping Company Name],
[Shipping Address Line 1],
[Shipping Address Line 2],
[Shipping Address Line 3],
[Shipping Address Line 4],
[Shipping Address Line 5],
[Shipping Telephone Number],
[Shipping Email Address],
[Credit Enabled],
[Credit Limit],
[Credit Limit Used],
[Credit Limit Used Percentage],
[Remaining Credit Limit],
[Payment Currency Id],
[Payment Currency Code],
[Payment Days],
[VAT Number],
[Global Parent Customer],
[Top Parent Customer],
[Active Status],
[Customer Since],
[Created Timestamp],
[Created By],
[Modified Timestamp],
[Modified By]
FROM [dbo].[vwCustomer]
WHERE [Customer Id] = @customerId