CREATE PROCEDURE [dbo].[spUpdateCustomer]
    @accountManagerId UNIQUEIDENTIFIER,
    @activeStatus BIT,
    @creditEnabled BIT,
    @creditLimit MONEY = NULL,
    @customerId UNIQUEIDENTIFIER,
    @customerSince DATE,
    @customerTierId UNIQUEIDENTIFIER,
    @customerTypeId UNIQUEIDENTIFIER,
    @globalParentCustomer BIT,
    @globalParentCustomerId UNIQUEIDENTIFIER = NULL,
    @salesRegionId UNIQUEIDENTIFIER,
    @billingFirstName NVARCHAR(20),
    @billingLastName NVARCHAR(30),
    @billingCompanyName NVARCHAR(50),
    @billingAddressLine1 NVARCHAR(50),
    @billingAddressLine2 NVARCHAR(50) = NULL,
    @billingAddressLine3 NVARCHAR(50),
    @billingAddressLine4 NVARCHAR(50),
    @billingAddressLine5 NVARCHAR(50),
    @billingTelephoneNumber NVARCHAR(50),
    @billingEmailAddress NVARCHAR(50),
    @paymentDays TINYINT,
    @shippingFirstName NVARCHAR(20),
    @shippingLastName NVARCHAR(30),
    @shippingCompanyName NVARCHAR(50),
    @shippingAddressLine1 NVARCHAR(50),
    @shippingAddressLine2 NVARCHAR(50) = NULL,
    @shippingAddressLine3 NVARCHAR(50),
    @shippingAddressLine4 NVARCHAR(50),
    @shippingAddressLine5 NVARCHAR(50),
    @shippingTelephoneNumber NVARCHAR(50),
    @shippingEmailAddress NVARCHAR(50),
    @topParentCustomer BIT,
    @topParentCustomerId UNIQUEIDENTIFIER = NULL,
    @vatNumber NVARCHAR(50) = NULL
AS

UPDATE [dbo].[Customer]
SET 
    [AccountManagerId] = @accountManagerId,
    [ActiveStatus] = @activeStatus,
    [CreditEnabled] = @creditEnabled,
    [CreditLimit] = @creditLimit,
    [CustomerSince] = @customerSince,
    [CustomerTierId] = @customerTierId,
    [CustomerTypeId] = @customerTypeId,
    [GlobalParentCustomer] = @globalParentCustomer,
    [GlobalParentCustomerId] = @globalParentCustomerId,
    [SalesRegionId] = @salesRegionId,
    [BillingFirstName] = @billingFirstName,
    [BillingLastName] = @billingLastName,
    [BillingCompanyName] = @billingCompanyName,
    [BillingAddressLine1] = @billingAddressLine1,
    [BillingAddressLine2] = @billingAddressLine2,
    [BillingAddressLine3] = @billingAddressLine3,
    [BillingAddressLine4] = @billingAddressLine4,
    [BillingAddressLine5] = @billingAddressLine5,
    [BillingTelephoneNumber] = @billingTelephoneNumber,
    [BillingEmailAddress] = @billingEmailAddress,
    [PaymentDays] = @paymentDays,
    [ShippingFirstName] = @shippingFirstName,
    [ShippingLastName] = @shippingLastName,
    [ShippingCompanyName] = @shippingCompanyName,
    [ShippingAddressLine1] = @shippingAddressLine1,
    [ShippingAddressLine2] = @shippingAddressLine2,
    [ShippingAddressLine3] = @shippingAddressLine3,
    [ShippingAddressLine4] = @shippingAddressLine4,
    [ShippingAddressLine5] = @shippingAddressLine5,
    [ShippingTelephoneNumber] = @shippingTelephoneNumber,
    [ShippingEmailAddress] = @shippingEmailAddress,
    [TopParentCustomer] = @topParentCustomer,
    [TopParentCustomerId] = @topParentCustomerId,
    [VATNumber] = @vatNumber
WHERE [CustomerId] = @customerId