CREATE PROCEDURE [dbo].[spCreateProduct]
    @activeStatus BIT,
    @manufacturerId UNIQUEIDENTIFIER,
    @manufacturerPartNumber NVARCHAR(50) = NULL,
    @productCountryOfOriginId UNIQUEIDENTIFIER,
    @productDescription NVARCHAR(255) = NULL,
    @productFamilyId UNIQUEIDENTIFIER = NULL,
    @productId UNIQUEIDENTIFIER OUTPUT,
    @productName NVARCHAR(50),
    @productSubCategoryId UNIQUEIDENTIFIER,
    @unitArea DECIMAL(5, 2),
    @unitBarcode NVARCHAR(50) = NULL,
    @unitDepthCentimeter DECIMAL(5, 2),
    @unitHeightCentimeter DECIMAL(5, 2),
    @unitMinimumStockQuantity INT,
    @unitPrice MONEY,
    @unitStockQuantityHeld INT,
    @unitVolumeCubicCentimeter DECIMAL(5, 2),
    @unitWeightKilogram DECIMAL(5, 2),
    @unitWidthCentimeter DECIMAL(5, 2),
    @wholesaleCartonArea DECIMAL(5, 2) = NULL,
    @wholesaleCartonBarcode NVARCHAR(50) = NULL,
    @wholesaleCartonDepthCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleCartonFlag BIT,
    @wholesaleCartonHeightCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleCartonPackagingWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesaleCartonQuantityPerPalletLevel TINYINT = NULL,
    @wholesaleCartonStackingHeightPerPallet TINYINT = NULL,
    @wholesaleCartonStockQuantityHeld BIGINT = NULL,
    @wholesaleCartonTotalWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesaleCartonVolumeCubicCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleCartonWidthCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleDeliveryTypeId UNIQUEIDENTIFIER = NULL,
    @wholesaleFlag BIT,
    @wholesalePalletArea DECIMAL(5, 2) = NULL,
    @wholesalePalletBarcode NVARCHAR(50) = NULL,
    @wholesalePalletDepthCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletFlag BIT,
    @wholesalePalletHeightCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletTotalHeightCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletTotalVolumeCubicCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletTotalWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesalePalletVolumeCubicCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesalePalletWidthCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleReorderFlag BIT,
    @wholesaleTotalCartonQuantityPerPallet INT = NULL,
    @wholesaleTotalUnitQuantityPerPallet INT = NULL,
    @wholesaleUnitQuantityPerCarton INT = NULL,
    @wholesaleUnitQuantityPerPalletLevel INT = NULL,
    @wholesaleUnitStackingHeightPerPallet TINYINT = NULL
AS

BEGIN
    BEGIN TRY
        SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
        BEGIN TRANSACTION;

        CREATE TABLE #ProductTemp
        (
            [ProductSubCategoryId] UNIQUEIDENTIFIER NOT NULL,
            [ProductName] NVARCHAR(50) NOT NULL,
            [ProductDescription] NVARCHAR(255) NULL,
            [ManufacturerId] UNIQUEIDENTIFIER NOT NULL,
            [ManufacturerPartNumber] NVARCHAR(50) NULL,
            [ProductCountryOfOriginId] UNIQUEIDENTIFIER NOT NULL,
            [ProductFamilyId] UNIQUEIDENTIFIER NULL,
            [WholesaleFlag] BIT NOT NULL,
            [WholesaleCartonFlag] BIT NOT NULL,
            [WholesaleCartonArea] DECIMAL(5, 2) NULL,
            [WholesaleCartonBarcode] NVARCHAR(50) NULL,
            [WholesaleUnitQuantityPerCarton] INT NULL,
            [WholesaleUnitQuantityPerPalletLevel] TINYINT NULL,
            [WholesaleTotalUnitQuantityPerPallet] INT NULL,
            [WholesaleUnitStackingHeightPerPallet] TINYINT NULL,
            [WholesaleCartonStockQuantityHeld] BIGINT NULL,
            [WholesaleCartonPackagingWeightKilogram] DECIMAL(5, 2) NULL,
            [WholesaleCartonTotalWeightKilogram] DECIMAL(5, 2) NULL,
            [WholesaleCartonHeightCentimeter] DECIMAL(5, 2) NULL,
            [WholesaleCartonWidthCentimeter] DECIMAL(5, 2) NULL,
            [WholesaleCartonDepthCentimeter] DECIMAL(5, 2) NULL,
            [WholesaleCartonVolumeCubicCentimeter] DECIMAL (5, 2) NULL,            
            [WholesalePalletFlag] BIT NOT NULL,
            [WholesalePalletArea] DECIMAL(5, 2) NULL,
            [WholesalePalletBarcode] NVARCHAR(50) NULL,
            [WholesaleCartonQuantityPerPalletLevel] TINYINT NULL,
            [WholesaleTotalCartonQuantityPerPallet] INT NULL,
            [WholesaleCartonStackingHeightPerPallet] TINYINT NULL,
            [WholesalePalletHeightCentimeter] DECIMAL(5, 2) NULL,
            [WholesalePalletWidthCentimeter] DECIMAL(5, 2) NULL,
            [WholesalePalletDepthCentimeter] DECIMAL(5, 2) NULL,
            [WholesalePalletVolumeCubicCentimeter] DECIMAL(5, 2) NULL,
            [WholesalePalletWeightKilogram] DECIMAL(5, 2) NULL,
            [WholesalePalletTotalHeightCentimeter] DECIMAL(5, 2) NULL,
            [WholesalePalletTotalVolumeCubicCentimeter] DECIMAL(5, 2) NULL,
            [WholesalePalletTotalWeightKilogram] DECIMAL(5, 2) NULL,
            [WholesaleDeliveryTypeId] UNIQUEIDENTIFIER NULL,
            [WholesaleReorderFlag] BIT NOT NULL,
            [UnitArea] DECIMAL(5, 2) NOT NULL,
            [UnitBarcode] NVARCHAR(50) NULL,
            [UnitPrice] MONEY NOT NULL,
            [UnitMinimumStockQuantity] INT NOT NULL,
            [UnitStockQuantityHeld] INT NOT NULL,
            [UnitWeightKilogram] DECIMAL(5, 2) NOT NULL,
            [UnitHeightCentimeter] DECIMAL(5, 2) NOT NULL,
            [UnitWidthCentimeter] DECIMAL(5, 2) NOT NULL,
            [UnitDepthCentimeter] DECIMAL(5, 2) NOT NULL,
            [UnitVolumeCubicCentimeter] DECIMAL(5, 2) NOT NULL,
            [ActiveStatus] BIT NOT NULL
        )

        INSERT INTO #ProductTemp
        (
            [ProductSubCategoryId],
            [ProductName],
            [ProductDescription],
            [ManufacturerId],
            [ManufacturerPartNumber],
            [ProductCountryOfOriginId],
            [ProductFamilyId],
            [WholesaleFlag],
            [WholesaleCartonFlag],
            [WholesaleCartonArea],
            [WholesaleCartonBarcode],
            [WholesaleUnitQuantityPerCarton],
            [WholesaleUnitQuantityPerPalletLevel],
            [WholesaleTotalUnitQuantityPerPallet],
            [WholesaleUnitStackingHeightPerPallet],
            [WholesaleCartonStockQuantityHeld],
            [WholesaleCartonPackagingWeightKilogram],
            [WholesaleCartonTotalWeightKilogram],
            [WholesaleCartonHeightCentimeter],
            [WholesaleCartonWidthCentimeter],
            [WholesaleCartonDepthCentimeter],
            [WholesaleCartonVolumeCubicCentimeter],
            [WholesalePalletFlag],
            [WholesalePalletArea],
            [WholesalePalletBarcode],
            [WholesaleCartonQuantityPerPalletLevel],
            [WholesaleTotalCartonQuantityPerPallet],
            [WholesaleCartonStackingHeightPerPallet],
            [WholesalePalletHeightCentimeter],
            [WholesalePalletWidthCentimeter],
            [WholesalePalletDepthCentimeter],
            [WholesalePalletVolumeCubicCentimeter],
            [WholesalePalletWeightKilogram],
            [WholesalePalletTotalHeightCentimeter],
            [WholesalePalletTotalVolumeCubicCentimeter],
            [WholesalePalletTotalWeightKilogram],
            [WholesaleDeliveryTypeId],
            [WholesaleReorderFlag],
            [UnitArea],
            [UnitBarcode],
            [UnitPrice],
            [UnitMinimumStockQuantity],
            [UnitStockQuantityHeld],
            [UnitWeightKilogram],
            [UnitHeightCentimeter],
            [UnitWidthCentimeter],
            [UnitDepthCentimeter],
            [UnitVolumeCubicCentimeter],
            [ActiveStatus]
        )
        VALUES
        (
            @productSubCategoryId,
            @productName,
            @productDescription,
            @manufacturerId,
            @manufacturerPartNumber,
            @productCountryOfOriginId,
            @productFamilyId,
            @wholesaleFlag,
            @wholesaleCartonFlag,
            @wholesaleCartonArea,
            @wholesaleCartonBarcode,
            @wholesaleUnitQuantityPerCarton,
            @wholesaleUnitQuantityPerPalletLevel,
            @wholesaleTotalUnitQuantityPerPallet,
            @wholesaleUnitStackingHeightPerPallet,
            @wholesaleCartonStockQuantityHeld,
            @wholesaleCartonPackagingWeightKilogram,
            @wholesaleCartonTotalWeightKilogram,
            @wholesaleCartonHeightCentimeter,
            @wholesaleCartonWidthCentimeter,
            @wholesaleCartonDepthCentimeter,
            @wholesaleCartonVolumeCubicCentimeter,
            @wholesalePalletFlag,
            @wholesalePalletArea,
            @wholesalePalletBarcode,
            @wholesaleCartonQuantityPerPalletLevel,
            @wholesaleTotalCartonQuantityPerPallet,
            @wholesaleCartonStackingHeightPerPallet,
            @wholesalePalletHeightCentimeter,
            @wholesalePalletWidthCentimeter,
            @wholesalePalletDepthCentimeter,
            @wholesalePalletVolumeCubicCentimeter,
            @wholesalePalletWeightKilogram,
            @wholesalePalletTotalHeightCentimeter,
            @wholesalePalletTotalVolumeCubicCentimeter,
            @wholesalePalletTotalWeightKilogram,
            @wholesaleDeliveryTypeId,
            @wholesaleReorderFlag,
            @unitArea,
            @unitBarcode,
            @unitPrice,
            @unitMinimumStockQuantity,
            @unitStockQuantityHeld,
            @unitWeightKilogram,
            @unitHeightCentimeter,
            @unitWidthCentimeter,
            @unitDepthCentimeter,
            @unitVolumeCubicCentimeter,
            @activeStatus
        )

        IF EXISTS (
            SELECT 1
            FROM [dbo].[Product] P
            INNER JOIN #ProductTemp PT ON P.[ManufacturerId] = PT.[ManufacturerId]
            AND P.[ProductName] = PT.[ProductName]
        )
        BEGIN
            DROP TABLE #ProductTemp;
            THROW 50000, 'Product already exists, please update the existing record.', 1;
        END

        DECLARE @InsertedProducts TABLE ([ProductId] UNIQUEIDENTIFIER);

        INSERT INTO [dbo].[Product]
        (
            [ProductSubCategoryId],
            [ProductName],
            [ProductDescription],
            [ManufacturerId],
            [ManufacturerPartNumber],
            [ProductCountryOfOriginId],
            [ProductFamilyId],
            [WholesaleFlag],
            [WholesaleCartonFlag],
            [WholesaleCartonArea],
            [WholesaleCartonBarcode],
            [WholesaleUnitQuantityPerCarton],
            [WholesaleUnitQuantityPerPalletLevel],
            [WholesaleTotalUnitQuantityPerPallet],
            [WholesaleUnitStackingHeightPerPallet],
            [WholesaleCartonStockQuantityHeld],
            [WholesaleCartonPackagingWeightKilogram],
            [WholesaleCartonHeightCentimeter],
            [WholesaleCartonWidthCentimeter],
            [WholesaleCartonDepthCentimeter],
            [WholesaleCartonTotalWeightKilogram],
            [WholesalePalletFlag],
            [WholesalePalletArea],
            [WholesalePalletBarcode],
            [WholesaleCartonQuantityPerPalletLevel],
            [WholesaleTotalCartonQuantityPerPallet],
            [WholesaleCartonStackingHeightPerPallet],
            [WholesalePalletHeightCentimeter],
            [WholesalePalletWidthCentimeter],
            [WholesalePalletDepthCentimeter],
            [WholesalePalletWeightKilogram],
            [WholesalePalletTotalHeightCentimeter],
            [WholesalePalletTotalWeightKilogram],
            [WholesaleDeliveryTypeId],
            [WholesaleReorderFlag],
            [UnitArea],
            [UnitBarcode],
            [UnitPrice],
            [UnitMinimumStockQuantity],
            [UnitStockQuantityHeld],
            [UnitWeightKilogram],
            [UnitHeightCentimeter],
            [UnitWidthCentimeter],
            [UnitDepthCentimeter],
            [ActiveStatus]
        )
        OUTPUT inserted.[ProductId] INTO @InsertedProducts
        SELECT
            [ProductSubCategoryId],
            [ProductName],
            [ProductDescription],
            [ManufacturerId],
            [ManufacturerPartNumber],
            [ProductCountryOfOriginId],
            [ProductFamilyId],
            [WholesaleFlag],
            [WholesaleCartonFlag],
            [WholesaleCartonArea],
            [WholesaleCartonBarcode],
            [WholesaleUnitQuantityPerCarton],
            [WholesaleUnitQuantityPerPalletLevel],
            [WholesaleTotalUnitQuantityPerPallet],
            [WholesaleUnitStackingHeightPerPallet],
            [WholesaleCartonStockQuantityHeld],
            [WholesaleCartonPackagingWeightKilogram],
            [WholesaleCartonHeightCentimeter],
            [WholesaleCartonWidthCentimeter],
            [WholesaleCartonDepthCentimeter],
            [WholesaleCartonTotalWeightKilogram],
            [WholesalePalletFlag],
            [WholesalePalletArea],
            [WholesalePalletBarcode],
            [WholesaleCartonQuantityPerPalletLevel],
            [WholesaleTotalCartonQuantityPerPallet],
            [WholesaleCartonStackingHeightPerPallet],
            [WholesalePalletHeightCentimeter],
            [WholesalePalletWidthCentimeter],
            [WholesalePalletDepthCentimeter],
            [WholesalePalletWeightKilogram],
            [WholesalePalletTotalHeightCentimeter],
            [WholesalePalletTotalWeightKilogram],
            [WholesaleDeliveryTypeId],
            [WholesaleReorderFlag],
            [UnitArea],
            [UnitBarcode],
            [UnitPrice],
            [UnitMinimumStockQuantity],
            [UnitStockQuantityHeld],
            [UnitWeightKilogram],
            [UnitHeightCentimeter],
            [UnitWidthCentimeter],
            [UnitDepthCentimeter],
            [ActiveStatus]
        FROM #ProductTemp;

        SELECT TOP 1 @productId = [ProductId] FROM @InsertedProducts;

        DROP TABLE #ProductTemp;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        THROW;
    END CATCH
END