CREATE PROCEDURE [dbo].[spUpdateProduct]
    @activeStatus BIT,
    @manufacturerId UNIQUEIDENTIFIER,
    @manufacturerPartNumber NVARCHAR(50) = NULL,
    @productCountryOfOriginId UNIQUEIDENTIFIER,
    @productDescription NVARCHAR(255) = NULL,
    @productFamilyId UNIQUEIDENTIFIER = NULL,
    @productId UNIQUEIDENTIFIER,
    @productName NVARCHAR(50),
    @productSubCategoryId UNIQUEIDENTIFIER,
    @unitArea DECIMAL(10, 2),
    @unitBarcode NVARCHAR(50) = NULL,
    @unitDepthCentimeter DECIMAL(5, 2),
    @unitHeightCentimeter DECIMAL(5, 2),
    @unitMinimumStockQuantity INT = NULL,
    @unitPrice MONEY,
    @unitStockQuantityHeld INT,
    @unitVolumeCubicCentimeter DECIMAL(12, 3),
    @unitWeightKilogram DECIMAL(5, 2),
    @unitWidthCentimeter DECIMAL(5, 2),
    @wholesaleCartonArea DECIMAL(10, 2) = NULL,
    @wholesaleCartonBarcode NVARCHAR(50) = NULL,
    @wholesaleCartonDepthCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleCartonFlag BIT,
    @wholesaleCartonHeightCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleCartonPackagingWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesaleCartonQuantityPerPalletLevel TINYINT = NULL,
    @wholesaleCartonStackingHeightPerPallet TINYINT = NULL,
    @wholesaleCartonStockQuantityHeld BIGINT = NULL,
    @wholesaleCartonTotalWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesaleCartonVolumeCubicCentimeter DECIMAL(12, 3) = NULL,
    @wholesaleCartonWidthCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleDeliveryTypeId UNIQUEIDENTIFIER = NULL,
    @wholesaleFlag BIT,
    @wholesalePalletArea DECIMAL(10, 2) = NULL,
    @wholesalePalletBarcode NVARCHAR(50) = NULL,
    @wholesalePalletDepthCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletFlag BIT,
    @wholesalePalletHeightCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletTotalHeightCentimeter DECIMAL(5, 2) = NULL,
    @wholesalePalletTotalVolumeCubicCentimeter DECIMAL(12, 3) = NULL,
    @wholesalePalletTotalWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesalePalletVolumeCubicCentimeter DECIMAL(12, 3) = NULL,
    @wholesalePalletWeightKilogram DECIMAL(5, 2) = NULL,
    @wholesalePalletWidthCentimeter DECIMAL(5, 2) = NULL,
    @wholesaleReorderFlag BIT,
    @wholesaleTotalCartonQuantityPerPallet INT = NULL,
    @wholesaleTotalUnitQuantityPerPallet INT = NULL,
    @wholesaleUnitQuantityPerCarton INT = NULL,
    @wholesaleUnitQuantityPerPalletLevel TINYINT = NULL,
    @wholesaleUnitStackingHeightPerPallet TINYINT = NULL
AS

BEGIN
    BEGIN TRY
        SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
        BEGIN TRANSACTION;

        UPDATE [dbo].[Product]
        SET
            [ActiveStatus] = @activeStatus,
            [ManufacturerId] = @manufacturerId,
            [ManufacturerPartNumber] = @manufacturerPartNumber,
            [ProductCountryOfOriginId] = @productCountryOfOriginId,
            [ProductDescription] = @productDescription,
            [ProductFamilyId] = @productFamilyId,
            [ProductName] = @productName,
            [ProductSubCategoryId] = @productSubCategoryId,
            [UnitArea] = @unitArea,
            [UnitBarcode] = @unitBarcode,
            [UnitDepthCentimeter] = @unitDepthCentimeter,
            [UnitHeightCentimeter] = @unitHeightCentimeter,
            [UnitMinimumStockQuantity] = @unitMinimumStockQuantity,
            [UnitPrice] = @unitPrice,
            [UnitStockQuantityHeld] = @unitStockQuantityHeld,
            [UnitVolumeCubicCentimeter] = @unitVolumeCubicCentimeter,
            [UnitWeightKilogram] = @unitWeightKilogram,
            [UnitWidthCentimeter] = @unitWidthCentimeter,
            [WholesaleCartonArea] = @wholesaleCartonArea,
            [WholesaleCartonBarcode] = @wholesaleCartonBarcode,
            [WholesaleCartonDepthCentimeter] = @wholesaleCartonDepthCentimeter,
            [WholesaleCartonFlag] = @wholesaleCartonFlag,
            [WholesaleCartonHeightCentimeter] = @wholesaleCartonHeightCentimeter,
            [WholesaleCartonQuantityPerPalletlevel] = @wholesaleCartonQuantityPerPalletLevel,
            [WholesaleCartonStackingHeightPerPallet] = @wholesaleCartonStackingHeightPerPallet,
            [WholesaleCartonStockQuantityHeld] = @wholesaleCartonStockQuantityHeld,
            [WholesaleCartonTotalWeightKilogram] = @wholesaleCartonTotalWeightKilogram,
            [WholesaleCartonVolumeCubicCentimeter] = @wholesaleCartonVolumeCubicCentimeter,
            [WholesaleCartonPackagingWeightKilogram] = @wholesaleCartonPackagingWeightKilogram,
            [WholesaleCartonWidthCentimeter] = @wholesaleCartonWidthCentimeter,
            [WholesaleDeliveryTypeId] = @wholesaleDeliveryTypeId,
            [WholesaleFlag] = @wholesaleFlag,
            [WholesalePalletArea] = @wholesalePalletArea,
            [WholesalePalletBarcode] = @wholesalePalletBarcode,
            [WholesalePalletDepthCentimeter] = @wholesalePalletDepthCentimeter,
            [WholesalePalletFlag] = @wholesalePalletFlag,
            [WholesalePalletHeightCentimeter] = @wholesalePalletHeightCentimeter,
            [WholesalePalletTotalHeightCentimeter] = @wholesalePalletTotalHeightCentimeter,
            [WholesalePalletTotalVolumeCubicCentimeter] = @wholesalePalletTotalVolumeCubicCentimeter,
            [WholesalePalletTotalWeightKilogram] = @wholesalePalletTotalWeightKilogram,
            [WholesalePalletVolumeCubicCentimeter] = @wholesalePalletVolumeCubicCentimeter,
            [WholesalePalletWeightKilogram] = @wholesalePalletWeightKilogram,
            [WholesalePalletWidthCentimeter] = @wholesalePalletWidthCentimeter,
            [WholesaleReorderFlag] = @wholesaleReorderFlag,
            [WholesaleTotalCartonQuantityPerPallet] = @wholesaleTotalCartonQuantityPerPallet,
            [WholesaleTotalUnitQuantityPerPallet] = @wholesaleTotalUnitQuantityPerPallet,
            [WholesaleUnitQuantityPerCarton] = @wholesaleUnitQuantityPerCarton,
            [WholesaleUnitQuantityPerPalletLevel] = @wholesaleUnitQuantityPerPalletLevel,
            [WholesaleUnitStackingHeightPerPallet] = @wholesaleUnitStackingHeightPerPallet
        WHERE [ProductId] = @productId

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        THROW;
    END CATCH
END