CREATE PROCEDURE [dbo].[spDeleteCustomerLeadType]
	@customerLeadTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE CLT
		FROM [dbo].[CustomerLeadType] CLT
		INNER JOIN [dbo].[MasterDataType] MDT ON CLT.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE CLT.[CustomerLeadTypeId] = @customerLeadTypeId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END