CREATE VIEW [dbo].[vwCustomer]
AS

SELECT
C.[GlobalParentCustomerId] AS [Global Parent Customer Id],
C.[TopParentCustomerId] AS [Top Parent Customer Id],
C.[CustomerId] AS [Customer Id],
CONCAT(AM.[FirstName], ' ', AM.[LastName]) AS [Account Manager],
AM.[AccountManagerId] AS [Account Manager Id],
CONCAT(CTI.[CustomerTierCode], ' ', CTI.[CustomerTierDescription]) AS [Customer Tier],
CTI.[CustomerTierId] AS [Customer Tier Id],
CTY.[CustomerType] AS [Customer Type],
SR.[SalesRegion] AS [Sales Region],
SR.[SalesRegionId] AS [Sales Region Id],
SSR.[SalesSubRegion] AS [Sales Sub Region],
SSR.[SalesSubRegionId] AS [Sales Sub Region Id],
C.[FirstName] AS [First Name],
C.[LastName] AS [Last Name],
C.[CompanyName] AS [Company Name],
C.[BillingFirstName] AS [Billing First Name],
C.[BillingLastName] AS [Billing Last Name],
C.[BillingCompanyName] AS [Billing Company Name],
C.[BillingAddressLine1] AS [Billing Address Line 1],
C.[BillingAddressLine2] AS [Billing Address Line 2],
C.[BillingAddressLine3] AS [Billing Address Line 3],
C.[BillingAddressLine4] AS [Billing Address Line 4],
C.[BillingAddressLine5] AS [Billing Address Line 5],
C.[BillingTelephoneNumber] AS [Billing Telephone Number],
C.[BillingEmailAddress] AS [Billing Email Address],
C.[ShippingFirstName] AS [Shipping First Name],
C.[ShippingLastName] AS [Shipping Last Name],
C.[ShippingCompanyName]	AS [Shipping Company Name],
C.[ShippingAddressLine1] AS [Shipping Address Line 1],
C.[ShippingAddressLine2] AS [Shipping Address Line 2],
C.[ShippingAddressLine3] AS [Shipping Address Line 3],
C.[ShippingAddressLine4] AS [Shipping Address Line 4],
C.[ShippingAddressLine5] AS [Shipping Address Line 5],
C.[ShippingTelephoneNumber] AS [Shipping Telephone Number],
C.[ShippingEmailAddress] AS [Shipping Email Address],
C.[CreditEnabled] AS [Credit Enabled],
C.[CreditLimit] AS [Credit Limit],
(SUM(CASE WHEN OS.[OrderStatus] != 'Settled' AND PM.[PaymentMethod] = 'Account Credit' THEN VOV.[TotalOrderValue] ELSE 0 END) / NULLIF(C.[CreditLimit], 0)) * 100 AS [Credit Limit Used Percentage],
(SUM(CASE WHEN OS.[OrderStatus] != 'Settled' AND PM.[PaymentMethod] = 'Account Credit' THEN VOV.[TotalOrderValue] ELSE 0 END)) AS [Credit Limit Used],
(SUM(CASE WHEN OS.[OrderStatus] != 'Settled' AND PM.[PaymentMethod] = 'Account Credit' THEN C.[CreditLimit] - VOV.[TotalOrderValue] ELSE 0 END)) AS [Remaining Credit Limit],
C.[PaymentDays] AS [Payment Days],
C.[VATNumber] AS [VAT Number],
C.[GlobalParentCustomer] AS [Global Parent Customer],
C.[TopParentCustomer] AS [Top Parent Customer],
C.[ActiveStatus] AS [Active Status],
C.[CustomerSince] AS [Customer Since],
C.[CreatedTimestamp] AS [Created Timestamp],
C.[CreatedBy] AS [Created By],
C.[ModifiedTimestamp] AS [Modified Timestamp],
C.[ModifiedBy] AS [Modified By]
FROM [dbo].[Customer] C
INNER JOIN [dbo].[AccountManager] AM ON C.[AccountManagerId] = AM.[AccountManagerId]
INNER JOIN [dbo].[CustomerTier] CTI ON C.[CustomerTierId] = CTI.[CustomerTierId]
INNER JOIN [dbo].[CustomerType] CTY ON C.[CustomerTypeId] = CTY.[CustomerTypeId]
INNER JOIN [dbo].[Order] O ON C.[CustomerId] = O.[CustomerId]
INNER JOIN [dbo].[OrderStatus] OS ON O.[OrderStatusId] = OS.[OrderStatusId]
INNER JOIN [dbo].[PaymentMethod] PM ON O.[PaymentMethodId] = PM.[PaymentMethodId]
INNER JOIN [dbo].[SalesSubRegion] SSR ON C.[SalesSubRegionId] = SSR.[SalesSubRegionId]
INNER JOIN [dbo].[SalesRegion] SR ON SSR.[SalesRegionId] = SR.[SalesRegionId]
INNER JOIN [dbo].[vwOrderValue] VOV ON O.[OrderId] = VOV.[OrderId]
GROUP BY
C.[GlobalParentCustomerId],
C.[TopParentCustomerId],
C.[CustomerId],
AM.[FirstName],
AM.[LastName],
AM.[AccountManagerId],
CTI.[CustomerTierCode],
CTI.[CustomerTierDescription],
CTI.[CustomerTierId],
CTY.[CustomerType],
SR.[SalesRegion],
SR.[SalesRegionId],
SSR.[SalesSubRegion],
SSR.[SalesSubRegionId],
C.[FirstName],
C.[LastName],
C.[CompanyName],
C.[BillingCompanyName],
C.[BillingFirstName],
C.[BillingLastName],
C.[BillingAddressLine1],
C.[BillingAddressLine2],
C.[BillingAddressLine3],
C.[BillingAddressLine4],
C.[BillingAddressLine5],
C.[BillingTelephoneNumber],
C.[BillingEmailAddress],
C.[ShippingCompanyName],
C.[ShippingFirstName],
C.[ShippingLastName],
C.[ShippingAddressLine1],
C.[ShippingAddressLine2],
C.[ShippingAddressLine3],
C.[ShippingAddressLine4],
C.[ShippingAddressLine5],
C.[ShippingTelephoneNumber],
C.[ShippingEmailAddress],
C.[CreditEnabled],
C.[CreditLimit],
C.[PaymentDays],
C.[VATNumber],
C.[GlobalParentCustomer],
C.[TopParentCustomer],
C.[ActiveStatus],
C.[CustomerSince],
C.[CreatedTimestamp],
C.[CreatedBy],
C.[ModifiedTimestamp],
C.[ModifiedBy]