CREATE PROCEDURE [dbo].[spDeleteProductImage]
	@productImageId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;
			DELETE FROM [dbo].[ProductImage]
			WHERE [ProductImageId] = @productImageId
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		THROW;
	END CATCH
END