CREATE PROCEDURE [dbo].[spDeleteCustomerLeadNoteType]
	@customerLeadNoteTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE CLNT
		FROM [dbo].[CustomerLeadNoteType] CLNT
		INNER JOIN [dbo].[MasterDataType] MDT ON CLNT.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE CLNT.[CustomerLeadNoteType] = @customerLeadNoteTypeId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END