CREATE PROCEDURE [dbo].[spGetAllMarketingChannel]
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

			SELECT
			[Marketing Channel Id],
			[Marketing Channel],
			[Active Status]
			FROM [dbo].[vwMarketingChannel]

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END