CREATE PROCEDURE [dbo].[spUpdateOrderInvoice]
	@orderInvoiceId UNIQUEIDENTIFIER,
	@orderInvoice VARBINARY(MAX)
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

			UPDATE [dbo].[OrderInvoice]
			SET 
				[OrderInvoice] = @orderInvoice
			WHERE [OrderInvoiceId] = @orderInvoiceId;

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END