CREATE PROCEDURE [dbo].[spDeleteWholesaleDeliveryType]
	@wholesaleDeliveryTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE FROM [dbo].[WholesaleDeliveryType]
		WHERE [WholesaleDeliveryTypeId] = @wholesaleDeliveryTypeId

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END