CREATE PROCEDURE [dbo].[spDeleteHTMLTemplateType]
	@htmlTemplateTypeId UNIQUEIDENTIFIER
AS

BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
		BEGIN TRANSACTION;

		DELETE HTMLTT
		FROM [dbo].[HTMLTemplateType] HTMLTT
		INNER JOIN [dbo].[MasterDataType] MDT ON HTMLTT.[MasterDataTypeId] = MDT.[MasterDataTypeId]
		WHERE HTMLTT.[HTMLTemplateTypeId] = @htmlTemplateTypeId
		AND MDT.[IsCustom] = 1

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;

		THROW;
	END CATCH
END